FROM python:3.7.1

RUN apt-get update && \
      apt-get -y install sudo

# If you need to install any non-python package that your package depends on, this is the place
# where you can do it. Look at the Docker documentation for that
